# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# The name we use for this project when interacting with Expeditor Slack App
project:
  alias: chef-analyze

# Slack channel in Chef Software slack to send notifications about build failure
slack:
  notify_channel: chef-ws-notify

github:
  # This deletes the GitHub PR branch after successfully merged into the release
  delete_branch_on_merge: true
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - trigger_pipeline:habitat/build:
      ignore_labels:
        - "Expeditor: Skip Habitat"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

pipelines:
  - verify:
      description: Pull Request validation tests
  - code_coverage:
      description: Generate code coverage reports and update local repository
      definition: .expeditor/coverage.pipeline.yml
  - habitat/build

promote:
  channels:
    - unstable
    - stable

subscriptions:
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages
  - workload: pull_request_merged:{{agent_id}}:*
    actions:
      - trigger_pipeline:code_coverage
